### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by adbinding** [Asiern/AutoThemeSwitch#7]
Can you tell me how to use it and how to customize the settings

**Comment by Asiern** [comment]
Navigate to your extensions, right click on `AutoThemeSwicth` and select `Extension Settings`. A new window called `Settings` should open. There you will find all the settings for the extension.
![Settings](https://user-images.githubusercontent.com/45818936/108827043-634e1200-75c5-11eb-8431-6d01c1e4a252.JPG)
